using System.Net.Http.Json;
using System.Text.Json;

var client = new HttpClient();
client.BaseAddress = new Uri("http://localhost:5038/swagger"); // Change url generated by Rest Api Solution after dotnet run
client.DefaultRequestHeaders.Add("Accept", "application/json");

// Random data
string[] firstNames = { "Leia", "Sadie", "Jose", "Sara", "Frank", "Dewey", "Tomas", "Joel", "Lukas", "Carlos" };
string[] lastNames = { "Liberty", "Ray", "Harrison", "Ronan", "Drew", "Powell", "Larsen", "Chan", "Anderson", "Lane" };

var random = new Random();
int idCounter = 1;

var tasks = new List<Task>();

for (int i = 0; i < 10; i++)
{
    tasks.Add(Task.Run(async () =>
    {
        var customers = new List<Customer>();

        for (int j = 0; j < 3; j++) // 3 customers per request asked
        {
            int age = random.Next(10, 90);
            customers.Add(new Customer
            {
                FirstName = firstNames[random.Next(firstNames.Length)],
                LastName = lastNames[random.Next(lastNames.Length)],
                Age = age,
                Id = Interlocked.Increment(ref idCounter)
            });
        }

        Console.WriteLine($"POSTing {customers.Count} customers...");
        var response = await client.PostAsJsonAsync("/customers", customers);
        Console.WriteLine($"POST status: {response.StatusCode}");

        if (!response.IsSuccessStatusCode)
        {
            var content = await response.Content.ReadAsStringAsync();
            Console.WriteLine($"Error: {content}");
        }

    }));
}

// Task to GET customers after POSTs
tasks.Add(Task.Run(async () =>
{
    await Task.Delay(3000);
    Console.WriteLine("\nFetching all customers information...");

    var customers = await client.GetFromJsonAsync<List<Customer>>("/customers");

    foreach (var c in customers)
    {
        Console.WriteLine($"{c.LastName}, {c.FirstName} - Age: {c.Age}, ID: {c.Id}");
    }
}));

await Task.WhenAll(tasks);

record Customer
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public int Age { get; set; }
    public int Id { get; set; }
}
